# Understanding Learning Curves

In [1]:
from datasets import load_dataset

# Dataset id from huggingface.co/dataset
dataset_id = "burtenshaw/PleIAs_common_corpus_code_classification"

# Load raw dataset
dataset = load_dataset(dataset_id)

In [2]:
print(len(dataset["train"]))
print(dataset["train"][0])

127723
{'text': '/*\n * Copyright (c) 2000 Kungliga Tekniska Högskolan\n * (Royal Institute of Technology, Stockholm, Sweden).\n * All rights reserved.\n *\n * Redistribution and use in source and binary forms, with or without\n * modification, are permitted provided that the following conditions\n * are met:\n *\n * 1. Redistributions of source code must retain the above copyright\n *    notice, this list of conditions and the following disclaimer.\n *\n * 2. Redistributions in binary form must reproduce the above copyright\n *    notice, this list of conditions and the following disclaimer in the\n *    documentation and/or other materials provided with the distribution.\n *\n * 3. Neither the name of the Institute nor the names of its contributors\n *    may be used to endorse or promote products derived from this software\n *    without specific prior written permission.\n *\n * THIS SOFTWARE IS PROVIDED BY THE INSTITUTE AND CONTRIBUTORS ``AS IS\'\' AND\n * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE\n * ARE DISCLAIMED.  IN NO EVENT SHALL THE INSTITUTE OR CONTRIBUTORS BE LIABLE\n * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS\n * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY\n * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF\n * SUCH DAMAGE.\n */\n\n#ifdef HAVE_CONFIG_H\n#include <config.h>\n__RCSID("$Heimdal: getaddrinfo_hostspec.c 14773 2005-04-12 11:29:18Z lha $"\n        "$NetBSD: getaddrinfo_hostspec.c,v 1.2 2008/03/22 08:37:21 mlelstv Exp $");\n#endif\n\n#include "roken.h"\n\n/* getaddrinfo via string specifying host and port */\n\nint ROKEN_LIB_FUNCTION\nroken_getaddrinfo_hostspec2(const char *hostspec,\n\t\t\t    int socktype,\n\t\t\t    int port,\n\t\t\t    struct addrinfo **ai)\n{\n    const char *p;\n    char portstr[NI_MAXSERV];\n    char host[MAXHOSTNAMELEN];\n    struct addrinfo hints;\n    int hostspec_len;\n\n    struct hst {\n\tconst char *prefix;\n\tint socktype;\n\tint protocol;\n\tint port;\n    } *hstp, hst[] = {\n\t{ "http://", SOCK_STREAM, IPPROTO_TCP, 80 },\n\t{ "http/", SOCK_STREAM, IPPROTO_TCP, 80 },\n\t{ "tcp/", SOCK_STREAM, IPPROTO_TCP },\n\t{ "udp/", SOCK_DGRAM, IPPROTO_UDP },\n\t{ NULL }\n    };\n\n    memset(&hints, 0, sizeof(hints));\n\n    hints.ai_socktype = socktype;\n\n    for(hstp = hst; hstp->prefix; hstp++) {\n\tif(strncmp(hostspec, hstp->prefix, strlen(hstp->prefix)) == 0) {\n\t    hints.ai_socktype = hstp->socktype;\n\t    hints.ai_protocol = hstp->protocol;\n\t    if(port == 0)\n\t\tport = hstp->port;\n\t    hostspec += strlen(hstp->prefix);\n\t    break;\n\t}\n    }\n\n    p = strchr (hostspec, \':\');\n    if (p != NULL) {\n\tchar *end;\n\n\tport = strtol (p + 1, &end, 0);\n\thostspec_len = p - hostspec;\n    } else {\n\thostspec_len = strlen(hostspec);\n    }\n    snprintf (portstr, sizeof(portstr), "%u", port);\n\n    snprintf (host, sizeof(host), "%.*s", hostspec_len, hostspec);\n    return getaddrinfo (host, portstr, &hints, ai);\n}\n\nint ROKEN_LIB_FUNCTION\nroken_getaddrinfo_hostspec(const char *hostspec,\n\t\t\t   int port,\n\t\t\t   struct addrinfo **ai)\n{\n    return roken_getaddrinfo_hostspec2(hostspec, 0, port, ai);\n}\n', 'labels': 'C'}

In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Model id to load the tokenizer'
model_id = "answerdotai/ModernBERT-base"

# Load Tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Prepare model labels - useful for inference
train_labels = sorted(set(dataset["train"]["labels"]))
label2id = {label: i for i, label in enumerate(train_labels)}
id2label = {i: label for label, i in label2id.items()}
num_labels = len(label2id)
dataset["test"] = dataset["test"].filter(lambda x: x["labels"] in label2id)

if "validation" in dataset:
    dataset["validation"] = dataset["validation"].filter(lambda x: x["labels"] in label2id)

# helper function
def preprocess(batch):
    # tokenize
    tokenized = tokenizer(batch['text'], padding=True, truncation=True, return_tensors="pt")
    # encode labels
    tokenized["labels"] = [label2id[label] for label in batch["labels"]]
    
    return tokenized


tokenized_dataset = dataset.map(preprocess, batched=True, remove_columns=["text"])

print(tokenized_dataset["train"].features.keys())
# dict_keys(['labels', 'input_ids', 'attention_mask'])

dict_keys(['labels', 'input_ids', 'attention_mask'])

In [4]:
# Download the model from huggingface.co/models
model = AutoModelForSequenceClassification.from_pretrained(
    model_id, num_labels=num_labels, label2id=label2id, id2label=id2label,
)

Loading weights:   0%|          | 0/136 [00:00<?, ?it/s]

ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-base
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.bias   | MISSING    |
classifier.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [5]:
# from transformers import AutoTokenizer, AutoModelForSequenceClassification, DataCollatorWithPadding

# # Model id to load the tokenizer
# model_id = "answerdotai/ModernBERT-base"

# # Load Tokenizer
# tokenizer = AutoTokenizer.from_pretrained(model_id)

# def tokenize_function(example):
#     return tokenizer(example["sentence1"], example["sentence2"], truncation=True)


# tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["sentence1", "sentence2", "idx"])
# data_collator = DataCollatorWithPadding(tokenizer=tokenizer)
# num_labels = len(set(tokenized_dataset["train"]["label"]))

In [6]:
# # Download the model from huggingface.co/models
# model = AutoModelForSequenceClassification.from_pretrained(
#     model_id, num_labels=num_labels)

In [7]:
import numpy as np
from sklearn.metrics import f1_score

# Metric helper method
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)
    score = f1_score(
            labels, predictions, labels=labels, pos_label=1, average="weighted"
        )
    return {"f1": float(score) if score == 1 else score}

In [ ]:
from huggingface_hub import get_token
from transformers import Trainer, TrainingArguments

# Define training args
training_args = TrainingArguments(
    output_dir= "ModernBERT-code-classifier",
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    gradient_accumulation_steps=1,
    learning_rate=5e-5,
    num_train_epochs=5,
    bf16=True, # bfloat16 training
    optim="adamw_torch_fused", # improved optimizer
    # logging & evaluation strategies
    logging_strategy="steps",
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    # push to hub parameters
    push_to_hub=True,
    hub_strategy="every_save",
    hub_token=get_token(),
    report_to="trackio",
    project="modernbert-code",
    trackio_space_id="ModernBert-code-classifier",
)

In [9]:
training_args

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=True,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_full_eval=False,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
full_determinism=False,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=True,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=None,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=100,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=f1,
neftune_noise_alpha=None,
num_train_epochs=5,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=ModernBERT-code-classifier,
parallelism_config=None,
per_device_eval_batch_size=32,
per_device_train_batch_size=1,
prediction_loss_only=False,
project=modernbert-code,
push_to_hub=True,
remove_unused_columns=True,
report_to=['trackio'],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=2,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_space_id=ModernBert-code-classifier,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=0,
weight_decay=0.0,
)

# Overfitting

In [10]:
limited_dataset = tokenized_dataset["train"].select(range(100))

# Create a Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=limited_dataset,
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics,
)
trainer.train()

* Trackio project initialized: modernbert-code
* Trackio metrics will be synced to Hugging Face Bucket: https://huggingface.co/buckets/hwting/ModernBert-code-classifier-bucket
* Found existing space: https://huggingface.co/spaces/hwting/ModernBert-code-classifier

* Created new run: hwting-1776059477

OutOfMemoryError: CUDA out of memory. Tried to allocate 4.00 GiB. GPU 0 has a total capacity of 15.61 GiB of which 1.83 GiB is free. Including non-PyTorch memory, this process has 13.76 GiB memory in use. Of the allocated memory 9.87 GiB is allocated by PyTorch, and 3.65 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://docs.pytorch.org/docs/stable/notes/cuda.html#optimizing-memory-usage-with-pytorch-cuda-alloc-conf)

In [ ]:
# clear memory

import torch
torch.cuda.empty_cache()

# del trainer
# del model
# del limited_dataset

# Underfitting

In [ ]:
# define a low learning rate
training_args.learning_rate = 1e-7

# Create a Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=limited_dataset,
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics,
)
trainer.train()

* Created new run: hwting-1775790874

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

* Run finished. Uploading logs to Trackio Space (please wait...)

TrainOutput(global_step=35, training_loss=0.1725019727434431, metrics={'train_runtime': 167.1579, 'train_samples_per_second': 2.991, 'train_steps_per_second': 0.209, 'total_flos': 17773316948940.0, 'train_loss': 0.1725019727434431, 'epoch': 5.0})

In [ ]:
# clear memory

import torch
torch.cuda.empty_cache()

# del trainer
# del model

# Just right! 🥣

In [ ]:
# define a valid learning rate
training_args.learning_rate = 5e-5

# Create a Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=limited_dataset,
    eval_dataset=tokenized_dataset["test"],
    compute_metrics=compute_metrics,
)
trainer.train()

* Created new run: hwting-1775791473

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

* Run finished. Uploading logs to Trackio Space (please wait...)

TrainOutput(global_step=35, training_loss=1.736484854561942, metrics={'train_runtime': 164.2516, 'train_samples_per_second': 3.044, 'train_steps_per_second': 0.213, 'total_flos': 17773316948940.0, 'train_loss': 1.736484854561942, 'epoch': 5.0})

# Inference

In [ ]:
from transformers import pipeline

# load model from huggingface.co/models using our repository id
classifier = pipeline(
    task="text-classification",
    model="hwting/ModernBERT-code-classifier",
    device=0,
)

sample = """def add_numbers(a, b):
    return a + b"""

classifier(sample)